### ISSUE TITLE
disabled style not changing on state change

### ISSUE THREAD

**Issue by trevorpfiz** [mrzachnugent/react-native-reusables#9]
On load the opacity is 50%. I change the state, but the opacity doesn't change.

My workaround is explicitly setting the disabled prop and a style:
```
const Button = React.forwardRef<
  React.ElementRef<typeof Pressable>,
  React.ComponentPropsWithoutRef<typeof Pressable> &
    VariantProps<typeof buttonVariants> & {
      textClass?: string;
    }
>(
  (
    {
      className,
      textClass,
      variant = "default",
      size,
      disabled,
      children,
      ...props
    },
    ref,
  ) => {
    const { colorScheme } = useColorScheme();

    // Define a style for the disabled state
    const disabledStyle = { opacity: disabled ? 0.5 : 1 };

    return (
      <Pressable
        className={cn(buttonVariants({ variant, size, className }))}
        ref={ref}
        style={disabledStyle}
        android_ripple={{
          color: rippleColor(colorScheme === "dark")[variant as "default"],
          borderless: false,
        }}
        disabled={disabled}
        {...props}
      >
```

**Comment by mrzachnugent** [comment]
Nice find, thanks.

This seems to be a native wind issue so I implemented your suggestion using className instead in this commit: 
You can see the changes on [components/ui/button.tsx - line 103](https://github.com/mrzachnugent/react-native-reusables/commit/69ded1a70e4966b4c68d360c3194d59dd1acd1d9#diff-2795b661f0806f90ae4821c33bdc2c7615156b270ec45bde4769727f4b6bc748)

**Comment by sudhanshug16** [comment]
I am still experiencing this issue and it is super weird. I moved to @trevorpfiz's solution to fix it for now.
